notifications:
  email: false

language: go

install: true

branches:
  only:
    - master

before_install:
  - |
      if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(.md)|(.html)|^(LICENSE)|^(docs)'
      then
        echo "Only docs were updated, not running the CI."
        exit
      fi

env:
- GO111MODULE=on

before_script:
- make install-linter

matrix:
  include:
  - go: "1.11.x"
    env: GOFLAGS=-mod=vendor
    script:
    - make lint
    # fails without -a
    - go test -a ./... # make test
  - go: "1.12.x"
    env: GOFLAGS=-mod=vendor
    script:
    - make lint
    # fails without -a
    - go test -a ./... # make test
